homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

frontend:
config:
http:
updater:
conversation:
history:
logbook:

sensor:
  - platform: uk_transport
    app_id: !secret uk_transport_app_id
    app_key: !secret uk_transport_app_key
    queries:
      - mode: bus
        origin: 340000368SHE
        destination: Wantage
      - mode: train
        origin: MAL
        destination: WIM

  - platform: template
    sensors:
      next_bus_route:
        friendly_name: 'Next bus route'
        value_template: '{{states.sensor.next_bus_to_wantage.attributes.next_buses[0].route}}'
      next_bus_direction:
        friendly_name: 'Next bus direction'
        value_template: '{{states.sensor.next_bus_to_wantage.attributes.next_buses[0].direction}}'
      next_bus_scheduled:
        friendly_name: 'Next bus scheduled'
        value_template: '{{states.sensor.next_bus_to_wantage.attributes.next_buses[0].scheduled}}'
      next_bus_estimated:
        friendly_name: 'Next bus estimated'
        value_template: '{{states.sensor.next_bus_to_wantage.attributes.next_buses[0].estimated}}'

      next_train_status:
        friendly_name: 'Next train status'
        value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].status}}'
      next_trains_origin:
        friendly_name: 'Next train origin'
        value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].origin_name}}'
      next_trains_estimated:
        friendly_name: 'Next train estimated'
        value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].estimated}}'
      next_trains_scheduled:
        friendly_name: 'Next train scheduled'
        value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].scheduled}}'
      next_trains_platform:
        friendly_name: 'Next train platform'
        value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].platform}}'
      next_trains_operator:
        friendly_name: 'Next train operator'
        value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].operator_name}}'

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.Train_group
      - group.Bus_group

  Bus_group:
    name: Bus
    entities:
      - sensor.next_bus_to_wantage
      - sensor.next_bus_route
      - sensor.next_bus_direction
      - sensor.next_bus_scheduled
      - sensor.next_bus_estimated

  Train_group:
    name: Trains
    entities:
      - sensor.next_train_to_wat
      - sensor.next_train_status
      - sensor.next_trains_estimated
      - sensor.next_trains_origin
      - sensor.next_trains_platform
      - sensor.next_trains_scheduled
      - sensor.next_trains_operator
